<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net10.0</TargetFramework><RestoreIgnoreFailedSources>false</RestoreIgnoreFailedSources></PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Hexalith.EventStore.Contracts" Version="3.106.0" />
    <PackageReference Include="Hexalith.EventStore.Client" Version="3.106.0" />
    <PackageReference Include="Hexalith.EventStore.Server" Version="3.106.0" />
    <PackageReference Include="Hexalith.EventStore.SignalR" Version="3.106.0" />
    <PackageReference Include="Hexalith.EventStore.Testing" Version="3.106.0" />
    <PackageReference Include="Hexalith.EventStore.Testing.Integration" Version="3.106.0" />
    <PackageReference Include="Hexalith.EventStore.Aspire" Version="3.106.0" />
    <PackageReference Include="Hexalith.EventStore.ServiceDefaults" Version="3.106.0" />
    <PackageReference Include="Hexalith.EventStore.DomainService" Version="3.106.0" />
    <PackageReference Include="Hexalith.EventStore.RestApi.Generators" Version="3.106.0" />
    <PackageReference Include="Hexalith.EventStore.Gateway" Version="3.106.0" />
    <PackageReference Include="Hexalith.EventStore.Admin.Abstractions" Version="3.106.0" />
    <PackageDownload Include="Hexalith.EventStore.Admin.Cli" Version="[3.106.0]" />
    <PackageReference Include="Hexalith.EventStore.Admin.Server" Version="3.106.0" />
  </ItemGroup>
</Project>
