// <copyright file="ClientGenerationTests.cs" company="Hexalith">
// Copyright (c) Hexalith. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace Hexalith.Projects.Client.Tests;

using System;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;

using Hexalith.Projects.Client.Generated;
using Hexalith.Projects.Client.Idempotency;
using Hexalith.Projects.Aggregates.Project;

using DomainCommands = Hexalith.Projects.Contracts.Commands;
using DomainIdentifiers = Hexalith.Projects.Contracts.Identifiers;
using DomainModels = Hexalith.Projects.Contracts.Models;

using Newtonsoft.Json;

using Shouldly;

using Xunit;

/// <summary>
/// Generation / provenance / fingerprint / hasher assertions for the Story 1.3 NSwag typed client and
/// the spine-driven idempotency helpers. Pure Tier-1: reads the checked-in generated artifacts from
/// disk, no network/containers/Dapr. The class name is <c>ClientGenerationTests</c> so the CI gate
/// filter (<c>FullyQualifiedName~...ClientGenerationTests</c>) can target it.
/// </summary>
public sealed class ClientGenerationTests
{
    private static readonly string RepositoryRoot = LocateRepositoryRoot();

    [Fact]
    public void NswagConfigurationUsesContractSpineAsOnlyInput()
    {
        string configurationPath = Path.Combine(RepositoryRoot, "src", "Hexalith.Projects.Client", "nswag.json");
        using JsonDocument document = JsonDocument.Parse(File.ReadAllText(configurationPath));

        JsonElement fromDocument = document.RootElement
            .GetProperty("documentGenerator")
            .GetProperty("fromDocument");
        JsonElement generator = document.RootElement
            .GetProperty("codeGenerators")
            .GetProperty("openApiToCSharpClient");

        // The spine is the ONLY input.
        fromDocument.GetProperty("url").GetString().ShouldBe("../../src/Hexalith.Projects.Contracts/openapi/hexalith.projects.v1.yaml");
        fromDocument.GetProperty("output").ValueKind.ShouldBe(JsonValueKind.Null);

        generator.GetProperty("newLineBehavior").GetString().ShouldBe("LF");
        generator.GetProperty("output").GetString().ShouldBe("Generated/HexalithProjectsClient.g.cs");
        generator.GetProperty("namespace").GetString().ShouldBe("Hexalith.Projects.Client.Generated");
        generator.GetProperty("exceptionClass").GetString().ShouldBe("HexalithProjectsApiException");
        generator.GetProperty("responseClass").GetString().ShouldBe("HexalithProjectsResponse");
        generator.GetProperty("injectHttpClient").GetBoolean().ShouldBeTrue();
        generator.GetProperty("disposeHttpClient").GetBoolean().ShouldBeFalse();
        generator.GetProperty("generateSyncMethods").GetBoolean().ShouldBeFalse();
        generator.GetProperty("generateClientInterfaces").GetBoolean().ShouldBeTrue();
        generator.GetProperty("generateExceptionClasses").GetBoolean().ShouldBeTrue();
        generator.GetProperty("useBaseUrl").GetBoolean().ShouldBeFalse();
        generator.GetProperty("jsonLibrary").GetString().ShouldBe("NewtonsoftJson");
        generator.GetProperty("dateType").GetString().ShouldBe("System.DateTimeOffset");
        generator.GetProperty("dateTimeType").GetString().ShouldBe("System.DateTimeOffset");
        generator.GetProperty("operationGenerationMode").GetString().ShouldBe("MultipleClientsFromOperationId");
    }

    [Fact]
    public void GeneratedClientCarriesAutoGeneratedHeaderAndIsSafe()
    {
        string generatedPath = Path.Combine(RepositoryRoot, "src", "Hexalith.Projects.Client", "Generated", "HexalithProjectsClient.g.cs");
        string generated = File.ReadAllText(generatedPath);

        generated.ShouldContain("<auto-generated>");
        generated.ShouldContain("Hexalith.Projects.Client.Generated");
        AssertGeneratedArtifactIsSafe(generated);

        // The seed command-async + freshness query types are present.
        generated.ShouldContain("class CreateProjectRequest");
        generated.ShouldContain("class ProjectLifecycleStatus");
        generated.ShouldContain("class ProjectListResponse");
        generated.ShouldContain("class LinkProjectConversationRequest");
        generated.ShouldContain("class MoveProjectConversationRequest");
        generated.ShouldContain("class UnlinkProjectConversationRequest");
        generated.ShouldContain("class ConfirmProjectResolutionRequest");
        generated.ShouldContain("class SetProjectFolderRequest");
        generated.ShouldContain("class LinkFileReferenceRequest");
        generated.ShouldContain("class UnlinkFileReferenceRequest");
        generated.ShouldContain("class LinkMemoryRequest");
        generated.ShouldContain("class UnlinkMemoryRequest");
        generated.ShouldContain("class ProjectFileReferenceMetadata");
        generated.ShouldContain("class ProjectConversationsPage");
        generated.ShouldContain("class ProjectCreationProposalRequest");
        generated.ShouldContain("class ProjectCreationProposal");
        generated.ShouldContain("class ConfirmNewProjectProposalRequest");
        generated.ShouldContain("class ProblemDetails");
    }

    [Fact]
    public void GeneratedHelpersCarryStableSafeProvenance()
    {
        string generatedPath = Path.Combine(RepositoryRoot, "src", "Hexalith.Projects.Client", "Generated", "HexalithProjectsIdempotencyHelpers.g.cs");
        string generated = File.ReadAllText(generatedPath);

        generated.ShouldContain("<auto-generated />");
        generated.ShouldContain("ContractSpineSha256");
        generated.ShouldContain("GenerationConfigurationSha256");
        generated.ShouldContain("GeneratedHelpersSha256");
        AssertGeneratedArtifactIsSafe(generated);
    }

    [Fact]
    public void GeneratedArtifactsAreLfOnly()
    {
        foreach (string fileName in new[] { "HexalithProjectsClient.g.cs", "HexalithProjectsIdempotencyHelpers.g.cs" })
        {
            byte[] bytes = File.ReadAllBytes(Path.Combine(RepositoryRoot, "src", "Hexalith.Projects.Client", "Generated", fileName));
            // No CR bytes at all (NSwag newLineBehavior: LF — documented generated exception to the CRLF rule).
            bytes.ShouldNotContain((byte)'\r', $"{fileName} must be LF-only.");
        }
    }

    [Fact]
    public void MutatingRequestExposesIdempotencyHelperAndQueryTypesDoNot()
    {
        Assembly clientAssembly = typeof(CreateProjectRequest).Assembly;

        foreach (Type requestType in new[]
        {
            typeof(CreateProjectRequest),
            typeof(UpdateProjectSetupRequest),
            typeof(ArchiveProjectRequest),
            typeof(RestoreProjectRequest),
            typeof(LinkProjectConversationRequest),
            typeof(MoveProjectConversationRequest),
            typeof(UnlinkProjectConversationRequest),
            typeof(ConfirmProjectResolutionRequest),
            typeof(SetProjectFolderRequest),
            typeof(LinkFileReferenceRequest),
            typeof(UnlinkFileReferenceRequest),
            typeof(LinkMemoryRequest),
            typeof(UnlinkMemoryRequest),
            typeof(ConfirmNewProjectProposalRequest),
        })
        {
            MethodInfo[] mutationMethods = requestType
                .GetMethods(BindingFlags.Instance | BindingFlags.Public)
                .Where(m => m.Name == "ComputeIdempotencyHash")
                .ToArray();
            mutationMethods.Length.ShouldBe(1, requestType.FullName);
            mutationMethods[0].ReturnType.ShouldBe(typeof(string));
        }

        // The seed query response type carries no idempotency helper.
        Type statusType = clientAssembly.GetType("Hexalith.Projects.Client.Generated.ProjectLifecycleStatus").ShouldNotBeNull();
        statusType.GetMethods(BindingFlags.Instance | BindingFlags.Public)
            .Any(m => m.Name == "ComputeIdempotencyHash").ShouldBeFalse();

        Type projectType = clientAssembly.GetType("Hexalith.Projects.Client.Generated.Project").ShouldNotBeNull();
        projectType.GetMethods(BindingFlags.Instance | BindingFlags.Public)
            .Any(m => m.Name == "ComputeIdempotencyHash").ShouldBeFalse();

        Type listResponseType = clientAssembly.GetType("Hexalith.Projects.Client.Generated.ProjectListResponse").ShouldNotBeNull();
        listResponseType.GetMethods(BindingFlags.Instance | BindingFlags.Public)
            .Any(m => m.Name == "ComputeIdempotencyHash").ShouldBeFalse();

        Type conversationsPageType = clientAssembly.GetType("Hexalith.Projects.Client.Generated.ProjectConversationsPage").ShouldNotBeNull();
        conversationsPageType.GetMethods(BindingFlags.Instance | BindingFlags.Public)
            .Any(m => m.Name == "ComputeIdempotencyHash").ShouldBeFalse();

        Type operatorDiagnosticType = clientAssembly.GetType("Hexalith.Projects.Client.Generated.ProjectOperatorDiagnostic").ShouldNotBeNull();
        operatorDiagnosticType.GetMethods(BindingFlags.Instance | BindingFlags.Public)
            .Any(m => m.Name == "ComputeIdempotencyHash").ShouldBeFalse();

        typeof(ProjectCreationProposalRequest).GetMethods(BindingFlags.Instance | BindingFlags.Public)
            .Any(m => m.Name == "ComputeIdempotencyHash").ShouldBeFalse();
        typeof(ProjectCreationProposal).GetMethods(BindingFlags.Instance | BindingFlags.Public)
            .Any(m => m.Name == "ComputeIdempotencyHash").ShouldBeFalse();
    }

    [Fact]
    public void GeneratedClientExposesListProjectsQueryWithoutIdempotencyParameter()
    {
        Assembly clientAssembly = typeof(CreateProjectRequest).Assembly;
        Type clientInterface = clientAssembly.GetType("Hexalith.Projects.Client.Generated.IClient").ShouldNotBeNull();

        MethodInfo[] listMethods = clientInterface.GetMethods(BindingFlags.Instance | BindingFlags.Public)
            .Where(m => m.Name == "ListProjectsAsync")
            .ToArray();

        listMethods.ShouldNotBeEmpty();
        listMethods.Any(m => m.ReturnType.FullName?.Contains("ProjectListResponse", StringComparison.Ordinal) == true).ShouldBeTrue();
        listMethods.SelectMany(m => m.GetParameters())
            .Any(p => p.Name?.Contains("idempotency", StringComparison.OrdinalIgnoreCase) == true)
            .ShouldBeFalse();
    }

    [Fact]
    public void GeneratedClientExposesAttachmentResolutionQueryWithoutIdempotencyParameter()
    {
        Assembly clientAssembly = typeof(CreateProjectRequest).Assembly;
        Type clientInterface = clientAssembly.GetType("Hexalith.Projects.Client.Generated.IClient").ShouldNotBeNull();

        MethodInfo[] methods = clientInterface.GetMethods(BindingFlags.Instance | BindingFlags.Public)
            .Where(m => m.Name == "ResolveProjectFromAttachmentsAsync")
            .ToArray();

        methods.ShouldNotBeEmpty();
        methods.Any(m => m.ReturnType.FullName?.Contains("ProjectResolution", StringComparison.Ordinal) == true).ShouldBeTrue();
        methods.SelectMany(m => m.GetParameters())
            .Any(p => p.Name?.Contains("idempotency", StringComparison.OrdinalIgnoreCase) == true)
            .ShouldBeFalse();
    }

    [Fact]
    public void GeneratedClientExposesOperatorDiagnosticsQueryWithoutIdempotencyParameter()
    {
        Assembly clientAssembly = typeof(CreateProjectRequest).Assembly;
        Type clientInterface = clientAssembly.GetType("Hexalith.Projects.Client.Generated.IClient").ShouldNotBeNull();

        MethodInfo[] methods = clientInterface.GetMethods(BindingFlags.Instance | BindingFlags.Public)
            .Where(m => m.Name == "GetProjectOperatorDiagnosticsAsync")
            .ToArray();

        methods.ShouldNotBeEmpty();
        methods.Any(m => m.ReturnType.FullName?.Contains("ProjectOperatorDiagnostic", StringComparison.Ordinal) == true).ShouldBeTrue();
        methods.SelectMany(m => m.GetParameters())
            .Any(p => p.Name?.Contains("idempotency", StringComparison.OrdinalIgnoreCase) == true)
            .ShouldBeFalse();
    }

    [Fact]
    public void GeneratedClientExposesProjectConversationOperationsWithExpectedIdempotencyShape()
    {
        Assembly clientAssembly = typeof(CreateProjectRequest).Assembly;
        Type clientInterface = clientAssembly.GetType("Hexalith.Projects.Client.Generated.IClient").ShouldNotBeNull();

        MethodInfo[] listMethods = clientInterface.GetMethods(BindingFlags.Instance | BindingFlags.Public)
            .Where(m => m.Name == "ListProjectConversationsAsync")
            .ToArray();
        listMethods.ShouldNotBeEmpty();
        listMethods.Any(m => m.ReturnType.FullName?.Contains("ProjectConversationsPage", StringComparison.Ordinal) == true).ShouldBeTrue();
        listMethods.SelectMany(m => m.GetParameters())
            .Any(p => p.Name?.Contains("idempotency", StringComparison.OrdinalIgnoreCase) == true)
            .ShouldBeFalse();

        foreach (string operation in new[] { "LinkProjectConversationAsync", "MoveProjectConversationAsync", "UnlinkProjectConversationAsync" })
        {
            MethodInfo[] methods = clientInterface.GetMethods(BindingFlags.Instance | BindingFlags.Public)
                .Where(m => m.Name == operation)
                .ToArray();
            methods.ShouldNotBeEmpty(operation);
            methods.SelectMany(m => m.GetParameters())
                .Any(p => string.Equals(p.Name, "idempotency_Key", StringComparison.Ordinal))
                .ShouldBeTrue(operation);
        }

        typeof(LinkProjectConversationRequest)
            .GetMethod("ComputeIdempotencyHash", [typeof(string), typeof(string)])
            .ShouldNotBeNull();
        typeof(MoveProjectConversationRequest)
            .GetMethod("ComputeIdempotencyHash", [typeof(string), typeof(string)])
            .ShouldNotBeNull();
        typeof(UnlinkProjectConversationRequest)
            .GetMethod("ComputeIdempotencyHash", [typeof(string), typeof(string)])
            .ShouldNotBeNull();
        typeof(ConfirmProjectResolutionRequest)
            .GetMethod("ComputeIdempotencyHash", [typeof(string), typeof(string)])
            .ShouldNotBeNull();
    }

    [Fact]
    public void GeneratedClientExposesConfirmProjectResolutionMutationWithoutFreshnessParameter()
    {
        Assembly clientAssembly = typeof(CreateProjectRequest).Assembly;
        Type clientInterface = clientAssembly.GetType("Hexalith.Projects.Client.Generated.IClient").ShouldNotBeNull();

        MethodInfo[] methods = clientInterface.GetMethods(BindingFlags.Instance | BindingFlags.Public)
            .Where(m => m.Name == "ConfirmProjectResolutionAsync")
            .ToArray();

        methods.ShouldNotBeEmpty();
        methods.Any(m => m.ReturnType.FullName?.Contains("AcceptedCommand", StringComparison.Ordinal) == true).ShouldBeTrue();
        methods.SelectMany(m => m.GetParameters())
            .Any(p => string.Equals(p.Name, "idempotency_Key", StringComparison.Ordinal))
            .ShouldBeTrue();
        methods.SelectMany(m => m.GetParameters())
            .Any(p => p.Name?.Contains("freshness", StringComparison.OrdinalIgnoreCase) == true)
            .ShouldBeFalse();
    }

    [Fact]
    public void GeneratedClientExposesNewProjectProposalPreviewAndConfirmShapes()
    {
        Assembly clientAssembly = typeof(CreateProjectRequest).Assembly;
        Type clientInterface = clientAssembly.GetType("Hexalith.Projects.Client.Generated.IClient").ShouldNotBeNull();

        MethodInfo[] previewMethods = clientInterface.GetMethods(BindingFlags.Instance | BindingFlags.Public)
            .Where(m => m.Name == "ProposeNewProjectAsync")
            .ToArray();
        previewMethods.ShouldNotBeEmpty();
        previewMethods.Any(m => m.ReturnType.FullName?.Contains("ProjectCreationProposal", StringComparison.Ordinal) == true).ShouldBeTrue();
        previewMethods.SelectMany(m => m.GetParameters())
            .Any(p => p.Name?.Contains("idempotency", StringComparison.OrdinalIgnoreCase) == true)
            .ShouldBeFalse();

        MethodInfo[] confirmMethods = clientInterface.GetMethods(BindingFlags.Instance | BindingFlags.Public)
            .Where(m => m.Name == "ConfirmNewProjectProposalAsync")
            .ToArray();
        confirmMethods.ShouldNotBeEmpty();
        confirmMethods.Any(m => m.ReturnType.FullName?.Contains("AcceptedCommand", StringComparison.Ordinal) == true).ShouldBeTrue();
        confirmMethods.SelectMany(m => m.GetParameters())
            .Any(p => string.Equals(p.Name, "idempotency_Key", StringComparison.Ordinal))
            .ShouldBeTrue();

        typeof(ConfirmNewProjectProposalRequest)
            .GetMethod("ComputeIdempotencyHash", Type.EmptyTypes)
            .ShouldNotBeNull();
    }

    [Fact]
    public void GeneratedClientExposesSetProjectFolderWithExpectedIdempotencyShape()
    {
        Assembly clientAssembly = typeof(CreateProjectRequest).Assembly;
        Type clientInterface = clientAssembly.GetType("Hexalith.Projects.Client.Generated.IClient").ShouldNotBeNull();

        MethodInfo[] methods = clientInterface.GetMethods(BindingFlags.Instance | BindingFlags.Public)
            .Where(m => m.Name == "SetProjectFolderAsync")
            .ToArray();
        methods.ShouldNotBeEmpty();
        methods.SelectMany(m => m.GetParameters())
            .Any(p => string.Equals(p.Name, "idempotency_Key", StringComparison.Ordinal))
            .ShouldBeTrue();

        typeof(SetProjectFolderRequest)
            .GetMethod("ComputeIdempotencyHash", [typeof(string)])
            .ShouldNotBeNull();
    }

    [Fact]
    public void CreateProjectHelperUsesDeclaredLexicographicFields()
    {
        var request = new CreateProjectRequest
        {
            ProjectMetadata = new ProjectMetadata
            {
                DisplayName = "Synthetic Project",
                MetadataClass = SensitiveMetadataTier.Tenant_sensitive,
            },
            RequestSchemaVersion = CreateProjectRequestRequestSchemaVersion.V1,
        };

        request.ComputeIdempotencyHash().ShouldBe(ExpectedHash(
            "operation=CreateProject",
            "field=project_metadata.display_name;present=true;value=s:Synthetic Project",
            "field=request_schema_version;present=true;value=s:v1"));
    }

    [Theory]
    [InlineData("CreateProject", 0x2028, "leading")]
    [InlineData("CreateProject", 0x2028, "embedded")]
    [InlineData("CreateProject", 0x2028, "trailing")]
    [InlineData("CreateProject", 0x2029, "leading")]
    [InlineData("CreateProject", 0x2029, "embedded")]
    [InlineData("CreateProject", 0x2029, "trailing")]
    [InlineData("UpdateProjectSetupGoals", 0x2028, "leading")]
    [InlineData("UpdateProjectSetupGoals", 0x2028, "embedded")]
    [InlineData("UpdateProjectSetupGoals", 0x2028, "trailing")]
    [InlineData("UpdateProjectSetupGoals", 0x2029, "leading")]
    [InlineData("UpdateProjectSetupGoals", 0x2029, "embedded")]
    [InlineData("UpdateProjectSetupGoals", 0x2029, "trailing")]
    [InlineData("UpdateProjectSetupInstructions", 0x2028, "leading")]
    [InlineData("UpdateProjectSetupInstructions", 0x2028, "embedded")]
    [InlineData("UpdateProjectSetupInstructions", 0x2028, "trailing")]
    [InlineData("UpdateProjectSetupInstructions", 0x2029, "leading")]
    [InlineData("UpdateProjectSetupInstructions", 0x2029, "embedded")]
    [InlineData("UpdateProjectSetupInstructions", 0x2029, "trailing")]
    [InlineData("SetProjectFolder", 0x2028, "leading")]
    [InlineData("SetProjectFolder", 0x2028, "embedded")]
    [InlineData("SetProjectFolder", 0x2028, "trailing")]
    [InlineData("SetProjectFolder", 0x2029, "leading")]
    [InlineData("SetProjectFolder", 0x2029, "embedded")]
    [InlineData("SetProjectFolder", 0x2029, "trailing")]
    [InlineData("LinkFileReference", 0x2028, "leading")]
    [InlineData("LinkFileReference", 0x2028, "embedded")]
    [InlineData("LinkFileReference", 0x2028, "trailing")]
    [InlineData("LinkFileReference", 0x2029, "leading")]
    [InlineData("LinkFileReference", 0x2029, "embedded")]
    [InlineData("LinkFileReference", 0x2029, "trailing")]
    [InlineData("LinkMemory", 0x2028, "leading")]
    [InlineData("LinkMemory", 0x2028, "embedded")]
    [InlineData("LinkMemory", 0x2028, "trailing")]
    [InlineData("LinkMemory", 0x2029, "leading")]
    [InlineData("LinkMemory", 0x2029, "embedded")]
    [InlineData("LinkMemory", 0x2029, "trailing")]
    public void SeparatorMetadata_MatchesRealDomainValidator(
        string operation,
        int separatorCodePoint,
        string position)
    {
        string value = PositionedValue("Synthetic Project", (char)separatorCodePoint, position);

        (ProjectCommandValidationResult Domain, string Generated) fingerprints = MutationFingerprints(operation, value);

        fingerprints.Domain.IsAccepted.ShouldBeTrue();
        fingerprints.Domain.IdempotencyFingerprint.ShouldBe(fingerprints.Generated);
    }

    [Theory]
    [InlineData("SetProjectFolder", 0x2028)]
    [InlineData("SetProjectFolder", 0x2029)]
    [InlineData("LinkFileReference", 0x2028)]
    [InlineData("LinkFileReference", 0x2029)]
    [InlineData("LinkMemory", 0x2028)]
    [InlineData("LinkMemory", 0x2029)]
    public void SeparatorOnlyOptionalDisplayMetadata_MatchesRealDomainValidator(
        string operation,
        int separatorCodePoint)
    {
        (ProjectCommandValidationResult Domain, string Generated) fingerprints = MutationFingerprints(
            operation,
            ((char)separatorCodePoint).ToString());

        fingerprints.Domain.IsAccepted.ShouldBeTrue();
        fingerprints.Domain.IdempotencyFingerprint.ShouldBe(fingerprints.Generated);
    }

    [Theory]
    [InlineData("CreateProject", 0x2028)]
    [InlineData("CreateProject", 0x2029)]
    [InlineData("UpdateProjectSetupGoals", 0x2028)]
    [InlineData("UpdateProjectSetupGoals", 0x2029)]
    [InlineData("UpdateProjectSetupInstructions", 0x2028)]
    [InlineData("UpdateProjectSetupInstructions", 0x2029)]
    [InlineData("SetProjectFolder", 0x2028)]
    [InlineData("SetProjectFolder", 0x2029)]
    [InlineData("LinkFileReference", 0x2028)]
    [InlineData("LinkFileReference", 0x2029)]
    [InlineData("LinkMemory", 0x2028)]
    [InlineData("LinkMemory", 0x2029)]
    public void SeparatorMetadata_ExactRawMaximumMatchesRealDomainValidator(
        string operation,
        int separatorCodePoint)
    {
        ArgumentNullException.ThrowIfNull(operation);
        int maximum = operation.StartsWith("UpdateProjectSetup", StringComparison.Ordinal) ? 512 : 160;
        string value = (char)separatorCodePoint + new string('a', maximum - 1);

        (ProjectCommandValidationResult Domain, string Generated) fingerprints = MutationFingerprints(operation, value);

        fingerprints.Domain.IsAccepted.ShouldBeTrue();
        fingerprints.Domain.IdempotencyFingerprint.ShouldBe(fingerprints.Generated);
    }

    [Theory]
    [InlineData("CreateProject")]
    [InlineData("UpdateProjectSetupGoals")]
    [InlineData("UpdateProjectSetupInstructions")]
    [InlineData("SetProjectFolder")]
    [InlineData("LinkFileReference")]
    [InlineData("LinkMemory")]
    public void MutationHelpers_KeepSeparatorsLfLiteralEscapesAndBaselineDistinct(string operation)
    {
        string[] hashes =
        [
            MutationFingerprints(operation, "Synthetic Project").Generated,
            GeneratedMutationFingerprint(operation, "Synthetic\nProject"),
            GeneratedMutationFingerprint(operation, "Synthetic\u2028Project"),
            GeneratedMutationFingerprint(operation, "Synthetic\u2029Project"),
            GeneratedMutationFingerprint(operation, "Synthetic\\u2028Project"),
            GeneratedMutationFingerprint(operation, "Synthetic\\u2029Project"),
        ];

        hashes.Distinct(StringComparer.Ordinal).Count().ShouldBe(hashes.Length);
    }

    [Fact]
    public void CreateProjectSeparatorFingerprints_ArePinnedAndDifferFromLegacyRawSeparators()
    {
        ProjectCommandValidationResult line = MutationFingerprints("CreateProject", "Synthetic\u2028Project").Domain;
        ProjectCommandValidationResult paragraph = MutationFingerprints("CreateProject", "Synthetic\u2029Project").Domain;

        line.IdempotencyFingerprint.ShouldBe("sha256:b8926519ad4db0115ce4d82416caf8ca9fb27fedd087fc90eb0032104f850d78");
        paragraph.IdempotencyFingerprint.ShouldBe("sha256:358216e481d29223f697a3a0023f5fe41ea8904894bd271c592b2fb7dec272bf");
        line.IdempotencyFingerprint.ShouldNotBe(ExpectedHash(
            "operation=CreateProject",
            "field=project_metadata.display_name;present=true;value=s:Synthetic\u2028Project",
            "field=request_schema_version;present=true;value=s:v1"));
    }

    [Fact]
    public void UpdateProjectSetupHelperUsesDeclaredLexicographicFields()
    {
        var request = new UpdateProjectSetupRequest
        {
            ProjectSetup = new ProjectSetup
            {
                Goals = ["keep continuity current"],
                UserInstructions = ["use safe project references"],
                PreferredSourceKinds = [ProjectContextSourceKind.Conversation, ProjectContextSourceKind.Memory],
                ExcludedSourceKinds = [ProjectContextSourceKind.FileReference],
                ConversationStartDefaults = new ConversationStartDefaults
                {
                    LinkedSourcePolicy = LinkedSourcePolicy.AuthorizedReferences,
                },
            },
            RequestSchemaVersion = UpdateProjectSetupRequestRequestSchemaVersion.V1,
        };

        request.ComputeIdempotencyHash().ShouldBe(ExpectedHash(
            "operation=UpdateProjectSetup",
            "field=project_setup.conversation_start_defaults.linked_source_policy;present=true;value=s:authorizedReferences",
            "field=project_setup.excluded_source_kinds;present=true;value=j:[\"fileReference\"]",
            "field=project_setup.goals;present=true;value=j:[\"keep continuity current\"]",
            "field=project_setup.preferred_source_kinds;present=true;value=j:[\"conversation\",\"memory\"]",
            "field=project_setup.user_instructions;present=true;value=j:[\"use safe project references\"]",
            "field=request_schema_version;present=true;value=s:v1"));
    }

    [Fact]
    public void UpdateProjectSetupHelperTreatsOmittedConversationDefaultsAsOmitted()
    {
        var request = new UpdateProjectSetupRequest
        {
            ProjectSetup = new ProjectSetup
            {
                Goals = ["Quote \" marker = ok; keep"],
                UserInstructions = ["Use metadata = yes; payload no"],
                PreferredSourceKinds = [ProjectContextSourceKind.Conversation],
                ExcludedSourceKinds = [],
                ConversationStartDefaults = null,
            },
            RequestSchemaVersion = UpdateProjectSetupRequestRequestSchemaVersion.V1,
        };

        request.ComputeIdempotencyHash().ShouldBe(ExpectedHash(
            "operation=UpdateProjectSetup",
            "field=project_setup.conversation_start_defaults.linked_source_policy;present=false;value=omitted",
            "field=project_setup.excluded_source_kinds;present=true;value=j:[]",
            "field=project_setup.goals;present=true;value=j:[\"Quote \\\" marker = ok; keep\"]",
            "field=project_setup.preferred_source_kinds;present=true;value=j:[\"conversation\"]",
            "field=project_setup.user_instructions;present=true;value=j:[\"Use metadata = yes; payload no\"]",
            "field=request_schema_version;present=true;value=s:v1"));
    }

    [Fact]
    public void ArchiveProjectHelperUsesDeclaredIntentAndSchemaVersion()
    {
        var request = new ArchiveProjectRequest
        {
            ArchiveIntent = ArchiveProjectRequestArchiveIntent.Archive,
            RequestSchemaVersion = ArchiveProjectRequestRequestSchemaVersion.V1,
        };

        request.ComputeIdempotencyHash().ShouldBe(ExpectedHash(
            "operation=ArchiveProject",
            "field=archive_intent;present=true;value=s:archive",
            "field=request_schema_version;present=true;value=s:v1"));
    }

    [Fact]
    public void RestoreProjectHelperUsesDeclaredIntentAndSchemaVersion()
    {
        var request = new RestoreProjectRequest
        {
            RequestSchemaVersion = RestoreProjectRequestRequestSchemaVersion.V1,
            RestoreIntent = RestoreProjectRequestRestoreIntent.Restore,
        };

        request.ComputeIdempotencyHash().ShouldBe(ExpectedHash(
            "operation=RestoreProject",
            "field=request_schema_version;present=true;value=s:v1",
            "field=restore_intent;present=true;value=s:restore"));
    }

    [Fact]
    public void LinkProjectConversationHelperUsesDeclaredLexicographicFields()
    {
        var request = new LinkProjectConversationRequest
        {
            RequestSchemaVersion = LinkProjectConversationRequestRequestSchemaVersion.V1,
            Operation = LinkProjectConversationRequestOperation.Link,
            ProjectId = "project_01HZY7Z6N7J4Q2X8Y9V0A1B2C3",
            ConversationId = "conversation_01HZY7Z6N7J4Q2X8Y9V0A1B2C4",
            ExpectedCurrentProjectId = "project_01HZY7Z6N7J4Q2X8Y9V0A1B2C3",
        };

        request.ComputeIdempotencyHash(request.ProjectId, request.ConversationId).ShouldBe(ExpectedHash(
            "operation=LinkProjectConversation",
            "field=conversation_id;present=true;value=s:conversation_01HZY7Z6N7J4Q2X8Y9V0A1B2C4",
            "field=expected_current_project_id;present=true;value=s:project_01HZY7Z6N7J4Q2X8Y9V0A1B2C3",
            "field=operation;present=true;value=s:link",
            "field=project_id;present=true;value=s:project_01HZY7Z6N7J4Q2X8Y9V0A1B2C3",
            "field=request_schema_version;present=true;value=s:v1"));
    }

    [Fact]
    public void MoveProjectConversationHelperUsesDeclaredLexicographicFields()
    {
        var request = new MoveProjectConversationRequest
        {
            RequestSchemaVersion = MoveProjectConversationRequestRequestSchemaVersion.V1,
            Operation = MoveProjectConversationRequestOperation.Move,
            ProjectId = "project_01HZY7Z6N7J4Q2X8Y9V0A1B2C5",
            ConversationId = "conversation_01HZY7Z6N7J4Q2X8Y9V0A1B2C4",
            SourceProjectId = "project_01HZY7Z6N7J4Q2X8Y9V0A1B2C3",
            Confirmed = true,
        };

        request.ComputeIdempotencyHash(request.ProjectId, request.ConversationId).ShouldBe(ExpectedHash(
            "operation=MoveProjectConversation",
            "field=confirmed;present=true;value=b:true",
            "field=conversation_id;present=true;value=s:conversation_01HZY7Z6N7J4Q2X8Y9V0A1B2C4",
            "field=operation;present=true;value=s:move",
            "field=project_id;present=true;value=s:project_01HZY7Z6N7J4Q2X8Y9V0A1B2C5",
            "field=request_schema_version;present=true;value=s:v1",
            "field=source_project_id;present=true;value=s:project_01HZY7Z6N7J4Q2X8Y9V0A1B2C3"));
    }

    [Fact]
    public void UnlinkProjectConversationHelperUsesDeclaredLexicographicFields()
    {
        var request = new UnlinkProjectConversationRequest
        {
            RequestSchemaVersion = UnlinkProjectConversationRequestRequestSchemaVersion.V1,
            Operation = UnlinkProjectConversationRequestOperation.Unlink,
            UnlinkIntent = UnlinkProjectConversationRequestUnlinkIntent.Clear,
            ProjectId = "project_01HZY7Z6N7J4Q2X8Y9V0A1B2C3",
            ConversationId = "conversation_01HZY7Z6N7J4Q2X8Y9V0A1B2C4",
        };

        request.ComputeIdempotencyHash(request.ProjectId, request.ConversationId).ShouldBe(ExpectedHash(
            "operation=UnlinkProjectConversation",
            "field=conversation_id;present=true;value=s:conversation_01HZY7Z6N7J4Q2X8Y9V0A1B2C4",
            "field=operation;present=true;value=s:unlink",
            "field=project_id;present=true;value=s:project_01HZY7Z6N7J4Q2X8Y9V0A1B2C3",
            "field=request_schema_version;present=true;value=s:v1",
            "field=unlink_intent;present=true;value=s:clear"));
    }

    [Fact]
    public void ConfirmProjectResolutionHelperUsesDeclaredLexicographicFields()
    {
        var request = new ConfirmProjectResolutionRequest
        {
            RequestSchemaVersion = ConfirmProjectResolutionRequestRequestSchemaVersion.V1,
            Operation = ConfirmProjectResolutionRequestOperation.Confirm,
            ProjectId = "project_01HZY7Z6N7J4Q2X8Y9V0A1B2C5",
            ConversationId = "conversation_01HZY7Z6N7J4Q2X8Y9V0A1B2C4",
            ResolutionResult = ConfirmProjectResolutionRequestResolutionResult.MultipleCandidates,
            Confirmed = true,
            CandidateProjectIds =
            [
                "project_01HZY7Z6N7J4Q2X8Y9V0A1B2C3",
                "project_01HZY7Z6N7J4Q2X8Y9V0A1B2C5",
            ],
            SourceProjectId = "project_01HZY7Z6N7J4Q2X8Y9V0A1B2C3",
        };

        request.ComputeIdempotencyHash(request.ProjectId, request.ConversationId).ShouldBe(ExpectedHash(
            "operation=ConfirmProjectResolution",
            "field=confirmed;present=true;value=b:true",
            "field=conversation_id;present=true;value=s:conversation_01HZY7Z6N7J4Q2X8Y9V0A1B2C4",
            "field=operation;present=true;value=s:confirm",
            "field=project_id;present=true;value=s:project_01HZY7Z6N7J4Q2X8Y9V0A1B2C5",
            "field=request_schema_version;present=true;value=s:v1",
            "field=resolution_result;present=true;value=s:MultipleCandidates",
            "field=source_project_id;present=true;value=s:project_01HZY7Z6N7J4Q2X8Y9V0A1B2C3"));
    }

    [Fact]
    public void ConfirmNewProjectProposalHelperUsesDeclaredLexicographicFields()
    {
        var request = new ConfirmNewProjectProposalRequest
        {
            RequestSchemaVersion = ConfirmNewProjectProposalRequestRequestSchemaVersion.V1,
            Operation = ConfirmNewProjectProposalRequestOperation.ConfirmNewProjectProposal,
            ResolutionResult = ConfirmNewProjectProposalRequestResolutionResult.NoMatch,
            Confirmed = true,
            ProjectId = "project_01HZY7Z6N7J4Q2X8Y9V0A1B2C3",
            ConversationId = "conversation_01HZY7Z6N7J4Q2X8Y9V0A1B2C4",
            ProjectMetadata = new ProjectMetadata
            {
                DisplayName = "synthetic-project-alpha",
                MetadataClass = SensitiveMetadataTier.Tenant_sensitive,
            },
            Description = "synthetic metadata description",
            SetupMetadata = "synthetic-setup-reference",
            Folder = new ConfirmNewProjectProposalFolder
            {
                FolderId = "folder_01HZY7Z6N7J4Q2X8Y9V0A1B2C7",
                FolderMetadata = new ProjectFolderMetadata { DisplayName = "synthetic-project-alpha" },
            },
            FileReferenceIds = ["file_01HZY7Z6N7J4Q2X8Y9V0A1B2D1"],
            FileReferences =
            [
                new ConfirmNewProjectProposalFileReference
                {
                    FileReferenceId = "file_01HZY7Z6N7J4Q2X8Y9V0A1B2D1",
                    FolderId = "folder_01HZY7Z6N7J4Q2X8Y9V0A1B2C7",
                    WorkspaceId = "workspace_01HZY7Z6N7J4Q2X8Y9V0A1B2D2",
                    FilePath = "docs/synthetic-note.md",
                    FileMetadata = new ProjectFileReferenceMetadata { DisplayName = "synthetic-note.md" },
                },
            ],
        };

        request.ComputeIdempotencyHash().ShouldBe(ExpectedHash(
            "operation=ConfirmNewProjectProposal",
            "field=conversation_id;present=true;value=s:conversation_01HZY7Z6N7J4Q2X8Y9V0A1B2C4",
            "field=description;present=true;value=s:synthetic metadata description",
            "field=file_reference_ids;present=true;value=j:[\"file_01HZY7Z6N7J4Q2X8Y9V0A1B2D1\"]",
            "field=folder.folder_id;present=true;value=s:folder_01HZY7Z6N7J4Q2X8Y9V0A1B2C7",
            "field=operation;present=true;value=s:confirmNewProjectProposal",
            "field=project_id;present=true;value=s:project_01HZY7Z6N7J4Q2X8Y9V0A1B2C3",
            "field=project_metadata.display_name;present=true;value=s:synthetic-project-alpha",
            "field=request_schema_version;present=true;value=s:v1",
            "field=resolution_result;present=true;value=s:NoMatch",
            "field=setup_metadata;present=true;value=s:synthetic-setup-reference"));
    }

    [Fact]
    public void SetProjectFolderHelperUsesDeclaredLexicographicFields()
    {
        var request = new SetProjectFolderRequest
        {
            RequestSchemaVersion = SetProjectFolderRequestRequestSchemaVersion.V1,
            Operation = SetProjectFolderRequestOperation.Set,
            ProjectId = "project_01HZY7Z6N7J4Q2X8Y9V0A1B2C3",
            FolderId = "folder_01HZY7Z6N7J4Q2X8Y9V0A1B2C7",
            FolderMetadata = new ProjectFolderMetadata
            {
                DisplayName = "Synthetic Folder",
            },
            ReplacementConfirmed = true,
        };

        request.ComputeIdempotencyHash(request.ProjectId).ShouldBe(ExpectedHash(
            "operation=SetProjectFolder",
            "field=folder_id;present=true;value=s:folder_01HZY7Z6N7J4Q2X8Y9V0A1B2C7",
            "field=folder_metadata.display_name;present=true;value=s:Synthetic Folder",
            "field=operation;present=true;value=s:set",
            "field=project_id;present=true;value=s:project_01HZY7Z6N7J4Q2X8Y9V0A1B2C3",
            "field=replacement_confirmed;present=true;value=b:true",
            "field=request_schema_version;present=true;value=s:v1"));
    }

    [Fact]
    public void GeneratedClientExposesFileReferenceOperationsWithExpectedIdempotencyShape()
    {
        Assembly clientAssembly = typeof(CreateProjectRequest).Assembly;
        Type clientInterface = clientAssembly.GetType("Hexalith.Projects.Client.Generated.IClient").ShouldNotBeNull();

        foreach (string operation in new[] { "LinkFileReferenceAsync", "UnlinkFileReferenceAsync" })
        {
            MethodInfo[] methods = clientInterface.GetMethods(BindingFlags.Instance | BindingFlags.Public)
                .Where(m => m.Name == operation)
                .ToArray();
            methods.ShouldNotBeEmpty(operation);
            methods.SelectMany(m => m.GetParameters())
                .Any(p => string.Equals(p.Name, "idempotency_Key", StringComparison.Ordinal))
                .ShouldBeTrue(operation);
        }

        typeof(LinkFileReferenceRequest)
            .GetMethod("ComputeIdempotencyHash", [typeof(string), typeof(string)])
            .ShouldNotBeNull();
        typeof(UnlinkFileReferenceRequest)
            .GetMethod("ComputeIdempotencyHash", [typeof(string), typeof(string)])
            .ShouldNotBeNull();
        typeof(LinkMemoryRequest)
            .GetMethod("ComputeIdempotencyHash", [typeof(string), typeof(string)])
            .ShouldNotBeNull();
        typeof(UnlinkMemoryRequest)
            .GetMethod("ComputeIdempotencyHash", [typeof(string), typeof(string)])
            .ShouldNotBeNull();
    }

    [Fact]
    public void LinkFileReferenceHelperUsesDeclaredLexicographicFields()
    {
        var request = new LinkFileReferenceRequest
        {
            RequestSchemaVersion = LinkFileReferenceRequestRequestSchemaVersion.V1,
            Operation = LinkFileReferenceRequestOperation.Link,
            ProjectId = "project_01HZY7Z6N7J4Q2X8Y9V0A1B2C3",
            FileReferenceId = "file_01HZY7Z6N7J4Q2X8Y9V0A1B2D1",
            FolderId = "folder_01HZY7Z6N7J4Q2X8Y9V0A1B2C7",
            WorkspaceId = "workspace_01HZY7Z6N7J4Q2X8Y9V0A1B2D2",
            FilePath = "docs/synthetic-note.md",
            FileMetadata = new ProjectFileReferenceMetadata { DisplayName = "synthetic-note.md" },
        };

        request.ComputeIdempotencyHash(request.ProjectId, request.FileReferenceId).ShouldBe(ExpectedHash(
            "operation=LinkFileReference",
            "field=file_metadata.display_name;present=true;value=s:synthetic-note.md",
            "field=file_reference_id;present=true;value=s:file_01HZY7Z6N7J4Q2X8Y9V0A1B2D1",
            "field=folder_id;present=true;value=s:folder_01HZY7Z6N7J4Q2X8Y9V0A1B2C7",
            "field=operation;present=true;value=s:link",
            "field=project_id;present=true;value=s:project_01HZY7Z6N7J4Q2X8Y9V0A1B2C3",
            "field=request_schema_version;present=true;value=s:v1"));
    }

    [Fact]
    public void UnlinkFileReferenceHelperUsesDeclaredLexicographicFields()
    {
        var request = new UnlinkFileReferenceRequest
        {
            RequestSchemaVersion = UnlinkFileReferenceRequestRequestSchemaVersion.V1,
            Operation = UnlinkFileReferenceRequestOperation.Unlink,
            UnlinkIntent = UnlinkFileReferenceRequestUnlinkIntent.RemoveReference,
            ProjectId = "project_01HZY7Z6N7J4Q2X8Y9V0A1B2C3",
            FileReferenceId = "file_01HZY7Z6N7J4Q2X8Y9V0A1B2D1",
        };

        request.ComputeIdempotencyHash(request.ProjectId, request.FileReferenceId).ShouldBe(ExpectedHash(
            "operation=UnlinkFileReference",
            "field=file_reference_id;present=true;value=s:file_01HZY7Z6N7J4Q2X8Y9V0A1B2D1",
            "field=operation;present=true;value=s:unlink",
            "field=project_id;present=true;value=s:project_01HZY7Z6N7J4Q2X8Y9V0A1B2C3",
            "field=request_schema_version;present=true;value=s:v1",
            "field=unlink_intent;present=true;value=s:removeReference"));
    }

    [Fact]
    public void LinkMemoryHelperUsesDeclaredLexicographicFields()
    {
        var request = new LinkMemoryRequest
        {
            RequestSchemaVersion = LinkMemoryRequestRequestSchemaVersion.V1,
            Operation = LinkMemoryRequestOperation.Link,
            ProjectId = "project_01HZY7Z6N7J4Q2X8Y9V0A1B2C3",
            MemoryReferenceId = "case_01HZY7Z6N7J4Q2X8Y9V0A1B2E1",
            MemoryMetadata = new ProjectMemoryReferenceMetadata { DisplayName = "synthetic-case-alpha" },
        };

        request.ComputeIdempotencyHash(request.ProjectId, request.MemoryReferenceId).ShouldBe(ExpectedHash(
            "operation=LinkMemory",
            "field=memory_metadata.display_name;present=true;value=s:synthetic-case-alpha",
            "field=memory_reference_id;present=true;value=s:case_01HZY7Z6N7J4Q2X8Y9V0A1B2E1",
            "field=operation;present=true;value=s:link",
            "field=project_id;present=true;value=s:project_01HZY7Z6N7J4Q2X8Y9V0A1B2C3",
            "field=request_schema_version;present=true;value=s:v1"));
    }

    [Fact]
    public void UnlinkMemoryHelperUsesDeclaredLexicographicFields()
    {
        var request = new UnlinkMemoryRequest
        {
            RequestSchemaVersion = UnlinkMemoryRequestRequestSchemaVersion.V1,
            Operation = UnlinkMemoryRequestOperation.Unlink,
            UnlinkIntent = UnlinkMemoryRequestUnlinkIntent.RemoveReference,
            ProjectId = "project_01HZY7Z6N7J4Q2X8Y9V0A1B2C3",
            MemoryReferenceId = "case_01HZY7Z6N7J4Q2X8Y9V0A1B2E1",
        };

        request.ComputeIdempotencyHash(request.ProjectId, request.MemoryReferenceId).ShouldBe(ExpectedHash(
            "operation=UnlinkMemory",
            "field=memory_reference_id;present=true;value=s:case_01HZY7Z6N7J4Q2X8Y9V0A1B2E1",
            "field=operation;present=true;value=s:unlink",
            "field=project_id;present=true;value=s:project_01HZY7Z6N7J4Q2X8Y9V0A1B2C3",
            "field=request_schema_version;present=true;value=s:v1",
            "field=unlink_intent;present=true;value=s:removeReference"));
    }

    [Fact]
    public void NullAndOmittedMetadataProduceDifferentCanonicalHashes()
    {
        var present = new CreateProjectRequest
        {
            ProjectMetadata = new ProjectMetadata { DisplayName = "Synthetic Project", MetadataClass = SensitiveMetadataTier.Tenant_sensitive },
            RequestSchemaVersion = CreateProjectRequestRequestSchemaVersion.V1,
        };
        var omitted = new CreateProjectRequest
        {
            ProjectMetadata = null,
            RequestSchemaVersion = CreateProjectRequestRequestSchemaVersion.V1,
        };

        present.ComputeIdempotencyHash().ShouldNotBe(omitted.ComputeIdempotencyHash());
    }

    [Fact]
    public void FingerprintVerifiesCurrentForCheckedInArtifacts()
    {
        HexalithProjectsGeneratedArtifacts.VerifyCurrentDetailed(RepositoryRoot).IsCurrent.ShouldBeTrue();
        // A relative root must fail closed (never a machine-local path leak).
        HexalithProjectsGeneratedArtifacts.VerifyCurrent("relative-root").ShouldBeFalse();
    }

    [Fact]
    public void FingerprintDetectsDriftInEachInput()
    {
        string spine = File.ReadAllText(Path.Combine(RepositoryRoot, "src", "Hexalith.Projects.Contracts", "openapi", "hexalith.projects.v1.yaml"));
        string configuration = File.ReadAllText(Path.Combine(RepositoryRoot, "src", "Hexalith.Projects.Client", "nswag.json"));
        string helpers = File.ReadAllText(Path.Combine(RepositoryRoot, "src", "Hexalith.Projects.Client", "Generated", "HexalithProjectsIdempotencyHelpers.g.cs"));

        // Baseline: the unmutated triple is current.
        HexalithProjectsGeneratedArtifacts.IsCurrent(spine, configuration, helpers).ShouldBeTrue();

        // Mutating any single input is detected as drift.
        HexalithProjectsGeneratedArtifacts.IsCurrent(spine + "\n# controlled stale-output test", configuration, helpers).ShouldBeFalse();
        HexalithProjectsGeneratedArtifacts.IsCurrent(spine, configuration.Replace("LF", "CRLF", StringComparison.Ordinal), helpers).ShouldBeFalse();
        HexalithProjectsGeneratedArtifacts.IsCurrent(spine, configuration, helpers + "\n// controlled stale-output test").ShouldBeFalse();
    }

    [Fact]
    public void VerifyCurrentDetailedDoesNotLeakAbsolutePaths()
    {
        // A fully-qualified but nonexistent root produces a path-relativized diagnostic.
        string fakeRoot = Path.Combine(Path.GetTempPath(), "hexalith-projects-missing-" + Guid.NewGuid().ToString("N"));
        HexalithProjectsGeneratedArtifactsVerification result = HexalithProjectsGeneratedArtifacts.VerifyCurrentDetailed(fakeRoot);

        result.IsCurrent.ShouldBeFalse();
        result.Diagnostic.ShouldNotContain(fakeRoot, Case.Insensitive);
    }

    [Fact]
    public void CanonicalHasherIsDeterministic()
    {
        IdempotencyField[] fields =
        [
            new IdempotencyField("a_field", true, "alpha"),
            new IdempotencyField("b_field", true, 42),
        ];

        HexalithIdempotencyHasher.Compute("Op", fields)
            .ShouldBe(HexalithIdempotencyHasher.Compute("Op", fields));
        HexalithIdempotencyHasher.Compute("Op", fields).ShouldStartWith("sha256:");
    }

    [Fact]
    public void CanonicalHasherEnforcesDeclaredOrder()
    {
        Should.Throw<InvalidOperationException>(() => HexalithIdempotencyHasher.Compute("Op", [
            new IdempotencyField("z_field", true, "last"),
            new IdempotencyField("a_field", true, "first"),
        ]));
    }

    [Fact]
    public void CanonicalHasherRejectsDuplicateField()
    {
        Should.Throw<InvalidOperationException>(() => HexalithIdempotencyHasher.Compute("Op", [
            new IdempotencyField("a_field", true, "first"),
            new IdempotencyField("a_field", true, "duplicate"),
        ]));
    }

    [Fact]
    public void CanonicalHasherEnforcesUtcDates()
    {
        Should.Throw<InvalidOperationException>(() => HexalithIdempotencyHasher.Compute("Op", [
            new IdempotencyField("when", true, DateTime.SpecifyKind(DateTime.UnixEpoch, DateTimeKind.Unspecified)),
        ]));

        // UTC is accepted.
        HexalithIdempotencyHasher.Compute("Op", [
            new IdempotencyField("when", true, DateTime.SpecifyKind(DateTime.UnixEpoch, DateTimeKind.Utc)),
        ]).ShouldStartWith("sha256:");
    }

    [Fact]
    public void CanonicalHasherRejectsControlCharacters()
    {
        // The canonical hasher rejects control characters in the operationId and in declared field
        // paths (the cross-surface idempotency contract — matches the Folders sibling). Control
        // characters inside string *values* are escaped, not rejected, so these assertions target the
        // operation and path surfaces where rejection is the contract.
        Should.Throw<InvalidOperationException>(() => HexalithIdempotencyHasher.Compute("Op\u0001", [
            new IdempotencyField("a_field", true, "value"),
        ]));

        Should.Throw<InvalidOperationException>(() => HexalithIdempotencyHasher.Compute("Op", [
            new IdempotencyField("bad\u0001field", true, "value"),
        ]));
    }

    [Fact]
    public void CanonicalHasherDistinguishesPresentFromOmitted()
    {
        string present = HexalithIdempotencyHasher.Compute("Op", [new IdempotencyField("v", true, null)]);
        string omitted = HexalithIdempotencyHasher.Compute("Op", [new IdempotencyField("v", false, null)]);
        present.ShouldNotBe(omitted);
    }

    private static void AssertGeneratedArtifactIsSafe(string generated)
    {
        generated.ShouldNotContain(RepositoryRoot, Case.Insensitive);
        generated.ShouldNotContain("https://", Case.Insensitive);
        generated.ShouldNotContain("provider_token", Case.Insensitive);
        generated.ShouldNotContain("credential_material", Case.Insensitive);
        generated.ShouldNotContain("-----BEGIN", Case.Insensitive);
    }

    private static (ProjectCommandValidationResult Domain, string Generated) MutationFingerprints(
        string operation,
        string value)
    {
        const string projectId = "project_01HZY7Z6N7J4Q2X8Y9V0A1B2C3";
        const string folderId = "folder_01HZY7Z6N7J4Q2X8Y9V0A1B2C7";
        const string fileId = "file_01HZY7Z6N7J4Q2X8Y9V0A1B2D1";
        const string memoryId = "case_01HZY7Z6N7J4Q2X8Y9V0A1B2E1";

        return operation switch
        {
            "CreateProject" => (
                ProjectCommandValidator.Validate(new DomainCommands.CreateProject(
                    "tenant-a",
                    new DomainIdentifiers.ProjectId(projectId),
                    value,
                    null,
                    null,
                    "actor-a",
                    "correlation-a",
                    "task-a",
                    "idempotency-a")),
                new CreateProjectRequest
                {
                    RequestSchemaVersion = CreateProjectRequestRequestSchemaVersion.V1,
                    ProjectMetadata = new ProjectMetadata
                    {
                        DisplayName = value,
                        MetadataClass = SensitiveMetadataTier.Tenant_sensitive,
                    },
                }.ComputeIdempotencyHash()),
            "UpdateProjectSetupGoals" => SetupFingerprints(value, separatorInGoals: true, projectId),
            "UpdateProjectSetupInstructions" => SetupFingerprints(value, separatorInGoals: false, projectId),
            "SetProjectFolder" => (
                ProjectCommandValidator.Validate(new DomainCommands.SetProjectFolder(
                    "tenant-a",
                    new DomainIdentifiers.ProjectId(projectId),
                    folderId,
                    new DomainModels.ProjectFolderMetadata(value),
                    ReplacementConfirmed: true,
                    "actor-a",
                    "correlation-a",
                    "task-a",
                    "idempotency-a")),
                new SetProjectFolderRequest
                {
                    RequestSchemaVersion = SetProjectFolderRequestRequestSchemaVersion.V1,
                    Operation = SetProjectFolderRequestOperation.Set,
                    ProjectId = projectId,
                    FolderId = folderId,
                    FolderMetadata = new ProjectFolderMetadata { DisplayName = value },
                    ReplacementConfirmed = true,
                }.ComputeIdempotencyHash(projectId)),
            "LinkFileReference" => (
                ProjectCommandValidator.Validate(new DomainCommands.LinkFileReference(
                    "tenant-a",
                    new DomainIdentifiers.ProjectId(projectId),
                    fileId,
                    folderId,
                    new DomainModels.ProjectFileReferenceMetadata(value),
                    "actor-a",
                    "correlation-a",
                    "task-a",
                    "idempotency-a")),
                new LinkFileReferenceRequest
                {
                    RequestSchemaVersion = LinkFileReferenceRequestRequestSchemaVersion.V1,
                    Operation = LinkFileReferenceRequestOperation.Link,
                    ProjectId = projectId,
                    FileReferenceId = fileId,
                    FolderId = folderId,
                    WorkspaceId = "workspace-a",
                    FilePath = "docs/file.md",
                    FileMetadata = new ProjectFileReferenceMetadata { DisplayName = value },
                }.ComputeIdempotencyHash(projectId, fileId)),
            "LinkMemory" => (
                ProjectCommandValidator.Validate(new DomainCommands.LinkMemory(
                    "tenant-a",
                    new DomainIdentifiers.ProjectId(projectId),
                    memoryId,
                    new DomainModels.ProjectMemoryReferenceMetadata(value),
                    "actor-a",
                    "correlation-a",
                    "task-a",
                    "idempotency-a")),
                new LinkMemoryRequest
                {
                    RequestSchemaVersion = LinkMemoryRequestRequestSchemaVersion.V1,
                    Operation = LinkMemoryRequestOperation.Link,
                    ProjectId = projectId,
                    MemoryReferenceId = memoryId,
                    MemoryMetadata = new ProjectMemoryReferenceMetadata { DisplayName = value },
                }.ComputeIdempotencyHash(projectId, memoryId)),
            _ => throw new ArgumentOutOfRangeException(nameof(operation), operation, "Unknown mutation operation."),
        };
    }

    private static (ProjectCommandValidationResult Domain, string Generated) SetupFingerprints(
        string value,
        bool separatorInGoals,
        string projectId)
    {
        string[] goals = separatorInGoals ? [value, "  sibling goal  "] : ["  sibling goal  "];
        string[] instructions = separatorInGoals ? ["  sibling instruction  "] : [value, "  sibling instruction  "];
        var domainSetup = new DomainModels.ProjectSetup(
            goals,
            instructions,
            [DomainModels.ProjectContextSourceKind.Conversation],
            [DomainModels.ProjectContextSourceKind.FileReference],
            new DomainModels.ConversationStartDefaults(DomainModels.LinkedSourcePolicy.AuthorizedReferences));
        var generatedSetup = new ProjectSetup
        {
            Goals = goals,
            UserInstructions = instructions,
            PreferredSourceKinds = [ProjectContextSourceKind.Conversation],
            ExcludedSourceKinds = [ProjectContextSourceKind.FileReference],
            ConversationStartDefaults = new ConversationStartDefaults
            {
                LinkedSourcePolicy = LinkedSourcePolicy.AuthorizedReferences,
            },
        };

        return (
            ProjectCommandValidator.Validate(new DomainCommands.UpdateProjectSetup(
                "tenant-a",
                new DomainIdentifiers.ProjectId(projectId),
                domainSetup,
                "actor-a",
                "correlation-a",
                "task-a",
                "idempotency-a")),
            new UpdateProjectSetupRequest
            {
                RequestSchemaVersion = UpdateProjectSetupRequestRequestSchemaVersion.V1,
                ProjectSetup = generatedSetup,
            }.ComputeIdempotencyHash());
    }

    private static string GeneratedMutationFingerprint(string operation, string value)
        => MutationFingerprints(operation, value).Generated;

    private static string PositionedValue(string value, char separator, string position)
        => position switch
        {
            "leading" => separator + value,
            "embedded" => value.Insert(value.Length / 2, separator.ToString()),
            "trailing" => value + separator,
            _ => throw new ArgumentOutOfRangeException(nameof(position), position, "Unknown separator position."),
        };

    private static string ExpectedHash(params string[] lines)
    {
        string canonical = string.Join('\n', lines);
        byte[] digest = SHA256.HashData(Encoding.UTF8.GetBytes(canonical));
        return "sha256:" + Convert.ToHexString(digest).ToLowerInvariant();
    }

    private static string LocateRepositoryRoot()
    {
        string assemblyLocation = typeof(ClientGenerationTests).Assembly.Location;
        string startDirectoryPath = string.IsNullOrEmpty(assemblyLocation)
            ? AppContext.BaseDirectory
            : (Path.GetDirectoryName(assemblyLocation) ?? AppContext.BaseDirectory);

        DirectoryInfo? directory = new(startDirectoryPath);
        while (directory is not null)
        {
            if (File.Exists(Path.Combine(directory.FullName, "Hexalith.Projects.slnx")))
            {
                return directory.FullName;
            }

            directory = directory.Parent;
        }

        throw new InvalidOperationException("Could not locate Hexalith.Projects.slnx from the test assembly location.");
    }
}
